### ISSUE TITLE
Causing doors to be invisible!

### ISSUE THREAD

**Issue by torialityy** [PandaDap2006/Pandas-Extra-Details#20]
On Fabric 1.14.22, whenever rejoining a server or dying, causes the doors and gates (unsure of trapdoors, signs or levers) to be invisible until interacted with.

**Comment by Henrique-Coder** [comment]
The same error happens to me, when I'm on Fabric 0.14.22-1.20.1 all the doors, trapdoors, levers and buttons become invisible when I enter a server, and only reappear when I interact with them. (note: I've only tested on PaperMC 1.20.1 servers and every time I go away from the item, it becomes invisible again, and I can only see its hitbox)

**Comment by PandaDap2006** [comment]
Im sorry about this to both of you, this is a known issue and has been fixed, but the update is not released yet, the reason behind this is because I want to make sure the mod works with mods like sodium, if you don't use sodium and want the fixed version, then it can be downloaded from my discord server in the announcement channel.
Again I'm really sorry, I will try to bring support as fast as possible.

**Comment by Henrique-Coder** [comment]
No problem, I can wait for the correction. I know how difficult this kind of correction is. Good luck!

**Comment by PandaDap2006** [comment]
This issue has been resolved in the latest update
